Add Django 2.0 support
caktus/django-sticky-uploads pull request #30
Opened 2018-03-26 17:56 UTC by dpoirier

2018-03-28 15:36 UTC, ironfroggy requested changes

2018-03-28 15:36 UTC, ironfroggy commented on setup.cfg
> +[bdist_wheel]
Can we add a blank line between sections

2018-03-28 15:36 UTC, ironfroggy commented on stickyuploads/__init__.py
> +__version__ = '0.7.0'
Sticky uploads has been around for a long time and this version breaks some major backwards compatibility. As good a time as any to cut a 1.0

2018-03-28 15:36 UTC, ironfroggy commented on tox.ini
> +envlist = {py34,py36}-2.0.X,{py27,py34,py36}-1.11.X,docs,flake8
Can we test 3.5 too, rather than skipping it between 3.4 and 3.6

2018-03-28 15:43 UTC, dpoirier commented
Good suggestions @ironfroggy . Updated.

2018-03-29 16:14 UTC, ironfroggy approved these changes

2018-03-29 19:23 UTC, merged